"use client";
import { AlignCenterHorizontal, AlignCenterVertical, Maximize, RotateCcw } from "lucide-react";
import { useStudioStore } from "@/store/studioStore";

function NumberField({ label, value, onChange, step = 1 }: { label: string; value: number; onChange(v: number): void; step?: number }) { return <label className="sf-num"><span>{label}</span><input type="number" value={Number(value.toFixed(2))} step={step} onChange={(e) => onChange(Number(e.target.value))}/></label>; }
export function PropertiesPanel() { const project = useStudioStore((s) => s.project), id = useStudioStore((s) => s.selectedSourceIds[0]), update = useStudioStore((s) => s.updateSource), updateT = useStudioStore((s) => s.updateTransform); const source = id ? project.sources[id] : undefined; if (!source) return <aside className="sf-properties"><header><h2>Properties</h2></header><div className="sf-empty sf-prop-empty">Select a source to edit its properties</div></aside>; const t = source.transform; return <aside className="sf-properties"><header><h2>Properties</h2><span>{source.type}</span></header><div className="sf-properties-scroll"><fieldset><legend>General</legend><label className="sf-field"><span>Name</span><input value={source.name} onChange={(e) => update(id, { name: e.target.value })}/></label><label className="sf-check"><input type="checkbox" checked={source.visible} onChange={(e) => update(id, { visible: e.target.checked })}/> Visible</label><label className="sf-check"><input type="checkbox" checked={source.locked} onChange={(e) => update(id, { locked: e.target.checked })}/> Locked</label><NumberField label="Opacity" value={source.opacity * 100} onChange={(v) => update(id, { opacity: Math.max(0,Math.min(1,v/100)) })}/></fieldset><fieldset><legend>Transform</legend><div className="sf-num-grid"><NumberField label="X" value={t.x} onChange={(x) => updateT(id,{x})}/><NumberField label="Y" value={t.y} onChange={(y) => updateT(id,{y})}/><NumberField label="Width" value={t.width} onChange={(width) => updateT(id,{width:Math.max(1,width)})}/><NumberField label="Height" value={t.height} onChange={(height) => updateT(id,{height:Math.max(1,height)})}/><NumberField label="Rotation" value={t.rotation} onChange={(rotation) => updateT(id,{rotation})}/></div><div className="sf-button-grid"><button onClick={() => updateT(id,{x:0,y:0,width:project.canvas.width,height:project.canvas.height})}><Maximize/>Fit</button><button onClick={() => updateT(id,{x:(project.canvas.width-t.width)/2})}><AlignCenterHorizontal/>Center H</button><button onClick={() => updateT(id,{y:(project.canvas.height-t.height)/2})}><AlignCenterVertical/>Center V</button><button onClick={() => updateT(id,{rotation:0,scaleX:1,scaleY:1,cropTop:0,cropRight:0,cropBottom:0,cropLeft:0})}><RotateCcw/>Reset</button></div></fieldset><fieldset><legend>Crop</legend><div className="sf-num-grid"><NumberField label="Top" value={t.cropTop} onChange={(cropTop) => updateT(id,{cropTop:Math.max(0,cropTop)})}/><NumberField label="Right" value={t.cropRight} onChange={(cropRight) => updateT(id,{cropRight:Math.max(0,cropRight)})}/><NumberField label="Bottom" value={t.cropBottom} onChange={(cropBottom) => updateT(id,{cropBottom:Math.max(0,cropBottom)})}/><NumberField label="Left" value={t.cropLeft} onChange={(cropLeft) => updateT(id,{cropLeft:Math.max(0,cropLeft)})}/></div></fieldset>
  {source.type === "text" && <fieldset><legend>Text</legend><textarea rows={4} value={source.text} onChange={(e) => update(id,{ text:e.target.value })}/><div className="sf-num-grid"><NumberField label="Font size" value={source.fontSize} onChange={(fontSize) => update(id,{fontSize} as Partial<typeof source>)}/><label className="sf-num"><span>Color</span><input type="color" value={source.color} onChange={(e) => update(id,{color:e.target.value} as Partial<typeof source>)}/></label></div></fieldset>}
  {source.type === "color" && <fieldset><legend>Color</legend><label className="sf-field"><span>Fill color</span><input type="color" value={source.color} onChange={(e) => update(id,{color:e.target.value} as Partial<typeof source>)}/></label></fieldset>}
  {source.type === "browser" && <fieldset><legend>Browser Source</legend><label className="sf-field"><span>URL</span><input value={source.url} onChange={(e) => update(id,{url:e.target.value} as Partial<typeof source>)}/></label><p className="sf-warning">Some sites block embedding with CSP or X-Frame-Options.</p></fieldset>}
  {["microphone","audio","video","display","webcam"].includes(source.type) && <fieldset><legend>Audio</legend><NumberField label="Volume" value={source.volume*100} onChange={(volume) => update(id,{volume:volume/100})}/><label className="sf-check"><input type="checkbox" checked={source.muted} onChange={(e) => update(id,{muted:e.target.checked})}/> Muted</label></fieldset>}
  </div></aside>; }

